### ISSUE TITLE
[Bug]: listActiveTickets command error

### ISSUE THREAD

**Issue by Seceroth** [someaddons/limitedchunks#11]
### Describe the bug you're experiencing

Using the '/limitedchunks listActiveTickets' command (in server console) gives the following error:
```
[Server thread/ERROR]: Command exception: /limitedchunks listActiveTickets -720 0 -1776
java.lang.NullPointerException: Cannot invoke "net.minecraft.util.collection.SortedArraySet.iterator()" because the return value of "it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.get(long)" is null
        at com.limitedchunks.Command.lambda$build$1(Command.java:34) ~[limitedchunks-fabric-1.20.1-4.0.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar:?]
        at net.minecraft.server.command.CommandManager.redirect$zlc000$architectury$performCommand(CommandManager.java:1545) ~[server-intermediary.jar:?]
        at net.minecraft.server.command.CommandManager.execute(CommandManager.java:287) ~[server-intermediary.jar:?]
        at net.minecraft.server.command.CommandManager.executeWithPrefix(CommandManager.java:280) ~[server-intermediary.jar:?]
        at net.minecraft.server.dedicated.MinecraftDedicatedServer.executeQueuedCommands(MinecraftDedicatedServer.java:299) ~[server-intermediary.jar:?]
        at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:284) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[Server thread/INFO]: An unexpected error occurred trying to execute that command
```

### Reproducability

Happens every time.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1 (<- not selectable in new issue template)

### Modloader version

Fabric

### Logs

Using Fabric limitedchunks-fabric-1.20.1-4.0.
And installed alongside the Prominence II modpack (https://modrinth.com/modpack/prominence-2-fabric)

**Comment by someaddons** [comment]
fixed in 4.1
